### ISSUE TITLE
Add a regex selector for paragraph text

### ISSUE THREAD

**Issue by themccubbins** [yshavit/mdq#140]
It would be nice to select paragraph text lines by regex.

**Comment by yshavit** [comment]
My main question here is what the syntax should be -- not for the regex itself, but for the "select paragraph' portion.

For most other elements, the syntax for the selector mirrors the markdown: `- matcher` for lists, `[matcher](matcher)` for links, etc. For paragraph text, there isn't any markdown to introduce it.

A few ideas I have:

1. #### naked matchers
   ```bash
   mdq '/foo/`
   ```
   - pro: mirrors the markdown
   - con: it makes paragraphs effectively the "default" item to select, which eh, feels wrong. If anything, the default should be "any item".
2. #### `P` for paragraph

   ```bash
   mdq 'P /foo/`
   ```
   - pro: explicit marker, and easy to remember
   - con: all the other selectors are symbols, which makes them visually distinct from unquoted matchers. `P` would be a exception (maybe the only one?)
4. Something else I'm not thinking of?

@themccubbins Do you have any thoughts / preferences? Do either of the options above jump out as obviously good or obviously bad?

**Comment by yshavit** [comment]
For posterity, I'm going to record an option I wrote down but then decided is bad:

#### Curly braces
```bash
mdq '{} /foo/`
# or
mdq '{P} /foo/`
```
- I already have ideas about using curlies for advanced options, for example on quoted strings (#56). This would extend that to selectors, and within that "advanted options" context, I could either make the empty selector or `P` mean paragraph.
- pro: the more I think of this, the fewer pros I can think for it
- con:
  - why do paragraphs -- the simplest of elements -- require "advanced options" that for other selectors are not even available?
  - if I never have the advanced options, this is even weirder
  - seriously why am I even listing this? I guess to remind myself later what a bad idea it is.

**Comment by yshavit** [comment]
Using syntax:

```
mdq 'P: /foo/`
```
